# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 02:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('content', models.IntegerField(default=-1)),
                ('is_updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(default=0)),
                ('commenttime', models.IntegerField(default=0)),
                ('commenter', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=512)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('courseid', models.CharField(max_length=128)),
                ('comments', models.CharField(default='[]', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('date', models.DateField()),
                ('content', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(default='', max_length=128)),
                ('receiver_id', models.CharField(default='', max_length=128)),
                ('content', models.CharField(default='', max_length=1024)),
                ('create_time', models.TimeField(default=datetime.datetime(2016, 12, 16, 10, 2, 53, 894878))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('username', models.CharField(db_index=True, default='', max_length=32)),
                ('department', models.CharField(default='', max_length=64)),
                ('position', models.CharField(default='', max_length=32)),
                ('email', models.CharField(default='', max_length=32)),
                ('realname', models.CharField(default='', max_length=32)),
                ('event_list', models.CharField(default='[]', max_length=256)),
            ],
        ),
    ]
