# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('username', models.CharField(db_index=True, default='', max_length=32, unique=True)),
                ('department', models.CharField(db_index=True, default='', max_length=64)),
                ('position', models.CharField(db_index=True, default='', max_length=32)),
                ('email', models.CharField(db_index=True, default='', max_length=32)),
                ('realname', models.CharField(db_index=True, default='', max_length=32)),
            ],
        ),
    ]
