# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id1', models.IntegerField(default=0)),
                ('open_id2', models.IntegerField(default=0)),
                ('content', models.IntegerField(default=-1)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2016, 12, 18, 13, 10, 31, 368736))),
                ('is_updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(default=0)),
                ('commenttime', models.IntegerField(default=0)),
                ('commenter', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=512)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('courseid', models.CharField(max_length=128)),
                ('comments', models.CharField(default='[]', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(default='', max_length=128)),
                ('receiver_id', models.CharField(default='', max_length=128)),
                ('content', models.CharField(default='', max_length=1024)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2016, 12, 18, 13, 10, 31, 369181))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('username', models.CharField(db_index=True, default='', max_length=32)),
                ('department', models.CharField(default='', max_length=64)),
                ('position', models.CharField(default='', max_length=32)),
                ('email', models.CharField(default='', max_length=32)),
                ('realname', models.CharField(default='', max_length=32)),
                ('event_list', models.CharField(default='[]', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WechatConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=1024)),
                ('jssdk_ticket', models.CharField(default='', max_length=1024)),
                ('access_token_expire_time', models.IntegerField(default=0)),
                ('jssdk_ticket_expire_time', models.IntegerField(default=0)),
            ],
        ),
    ]
