# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20161204_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.IntegerField()),
                ('content', models.CharField(default='', max_length=512)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('courseid', models.CharField(max_length=128)),
                ('comments', models.CharField(default='[]', max_length=1024)),
            ],
        ),
    ]
