# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_comment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
