# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20161207_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenttime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='courseid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.IntegerField(default=0),
        ),
    ]
